### ISSUE TITLE
Error handling with effect

### ISSUE THREAD

**Issue by feitzi** [ngneat/effects#30]
### Which @ngneat/effects-* package(s) are the source of the bug?

effects-ng

### Is this a regression?

No

### Description

If an effect returns an unhandled exception, it can not be started again. For me its seems like a bug, or some kind of missing documentation to handle errors.
It's possible to use `catchError`, but there should be a more generic way to solve that problem?

From my submitted sample: 
![image](https://user-images.githubusercontent.com/2361489/179285785-dab4049c-0c89-4fa1-a3b1-4c2a2824fb6b.png)

### Please provide a link to a minimal reproduction of the bug

https://codesandbox.io/s/elfeffectserrorhandling-oo7qvf?file=/src/app/app.component.ts

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Use tapResult. See readme.

**Comment by feitzi** [comment]
I updated the [sample](https://codesandbox.io/s/elfeffectserrorhandling-oo7qvf?file=/src/app/app.component.ts), and it doesn't work like described in the [readme](https://github.com/ngneat/effects/blob/7f6b590382b8877453ab2051be4b10aced6903ec/README.md#:~:text=The%20tapResult%20operator%20safely%20handles%20the%20result.%20It%20enforces%20that%20the%20effect%20would%20still%20be%20running%20in%20case%20of%20error.%20Finally%2C%20we%20can%20dispatch%20actions%20using%20the%20dispatch%20function%3A)

Can you please adapt my minimal sandbox example to show a working error handling? Maybe then I can create a PR with documentation on this topic for other people.

**Comment by NetanelBasal** [comment]
It should be in the inner observable:

```ts
  sampleEffect = this.createEffectFn(($: Observable<number>) =>
    $.pipe(
      switchMap(() => { 
        return from(fetch('https://not-exists')).pipe(
          tapResult(
            (x) => console.log("Further processing of:", x),
            (error) => console.error(error)
          )
        )
      }),
    )
  );
```
