### ISSUE TITLE
Dispatching effects throw an error

### ISSUE THREAD

**Issue by frango9000** [ngneat/effects#42]
### Which @ngneat/effects-* package(s) are the source of the bug?

effects

### Is this a regression?

No

### Description

Effects are throwing an error when dispatched.

When following the Documentation example:

`
  loadTodos$ = createEffect(actions => actions.pipe(
    ofType(loadTodos),
    switchMap((todo) => this.todosApi.loadTodos())
  ));
`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-mctwxe?file=src/main.ts

### Please provide the exception or error you saw

```true
ERROR
Error: Make sure to provide a valid action type or set the option {dispatch: false}
```

### Please provide the environment you discovered this bug in

```true
"@ngneat/effects": "2.1.0",
        "@ngneat/effects-ng": "3.0.0",
```

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
@EricPoul, Do we handle it in your last PR that we merged?

**Comment by EricPoul** [comment]
Nope, it's a bug. I see it. I'll make a pr to fix it
