### ISSUE TITLE
Not supported for @angular/router@15.2.1

### ISSUE THREAD

**Issue by utpaulBS23** [ngneat/effects#45]
### Which @ngneat/effects-* package(s) are the source of the bug?

effects-ng

### Is this a regression?

Yes

### Description

Hi, I'm using node version 18.14. I'm getting a problem after uprating my angular version 14 to 15. I saw it's a peer dependency.
Here is the screenshot.

<img width="755" alt="Screen Shot 2023-03-04 at 5 49 13 PM" src="https://user-images.githubusercontent.com/56062199/222899198-a4c9f82c-bd9c-450b-ac3d-4c079cf4b2ee.png">

### Please provide the environment you discovered this bug in

Node version 18.14.0 and npm version 9.3.1 angular cil  15.2.1

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
@EricPoul

**Comment by EricPoul** [comment]
I added a router for test purposes and didn't add to the `peerDependencies`. Should I leave tests and add `router` to `peerDependencies`?

**Comment by NetanelBasal** [comment]
How the router related to the library?

**Comment by EricPoul** [comment]
Only imports in tests for checking lazy provided effects

**Comment by EricPoul** [comment]
I think I should rewrite a test a little to only depend on `@angular/router/testing`

**Comment by EricPoul** [comment]
I see in tests in `NGRX` they depend on both `@angular/router/testing` and `@angular/router`. They do not add it in `peerDependencies`.

**Comment by NetanelBasal** [comment]
I don't understand how the router is related. The only dependency is Angular:

https://github.com/ngneat/effects/blob/master/libs/effects-ng/package.json#L39

**Comment by EricPoul** [comment]
Yes, I know, it's strange. I could find a similar issue and a few referenced issues inside.

**Comment by utpaulBS23** [comment]
Do you resolve this issue @EricPoul ?

**Comment by EricPoul** [comment]
Not yet. I can't just update every angular version. Use `--legacy-peer-deps` for now. I'll try to research what we can do.

**Comment by utpaulBS23** [comment]
@EricPoul you do research and make it comparable with all angular version

**Comment by EricPoul** [comment]
@NetanelBasal Hard to test it until it's merged. I went through ngrx repo to check what the problem can be. The only thing I think can differs is that they store all specs in the `specs` folder which is on the same level as `src` folder.

**Comment by EricPoul** [comment]
I've just installed `@ngrx/effects` that uses `Router` in its test and it hasn't argue about `peedDependencies`.

**Comment by NetanelBasal** [comment]
There is no reason that it will yell in our library. It's not a dependency. Did you try it yourself?

**Comment by EricPoul** [comment]
Not in our lib. I'm testing in the new test angular app `^15.2.1`

**Comment by EricPoul** [comment]
It yells. When I build `effects-ng` I see `@angular/router` added to peer deps. I think I should check NX config.

**Comment by NetanelBasal** [comment]
Oh yes, It's Nx. They have a configuration to disable it

**Comment by EricPoul** [comment]
Yes, I encountered it as I remember but didn't think that it was actually NX

**Comment by NetanelBasal** [comment]
Yes, I know this issue and use it in my repositories. https://github.com/ngneat/elf/blob/master/packages/store/project.json#L10
