### ISSUE TITLE
Jest suits fail

### ISSUE THREAD

**Issue by frango9000** [ngneat/effects#46]
### Which @ngneat/effects-* package(s) are the source of the bug?

effects

### Is this a regression?

No

### Description

After updating to from v1.1.1 to v2.1.1 Jest suits started failing

`

    SyntaxError: Cannot use import statement outside a module

      1 | import { Component } from '@angular/core';
    > 2 | import {Actions} from "@ngneat/effects-ng";
        | ^

`

Here is the log output of a reproduction example:
https://github.com/frango9000/effects-jest/actions/runs/4332758127/jobs/7565462273

Also noticed that the output in node_modules folder is different:
v1.1.1
![image](https://user-images.githubusercontent.com/43641397/222928047-2da91427-8216-45a3-b4df-e9aa0811b6aa.png)
v2.1.1
![image](https://user-images.githubusercontent.com/43641397/222928061-9a243a6f-1dd9-4fe6-9fff-0fe3478a2519.png)

### Please provide a link to a minimal reproduction of the bug

https://github.com/frango9000/effects-jest

### Please provide the exception or error you saw

```true
FAIL effects-jest apps/effects-jest/src/app/app.component.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/runner/work/effects-jest/effects-jest/node_modules/@ngneat/effects/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { Subject, Observable, EMPTY } from 'rxjs';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { Component } from '@angular/core';
    > 2 | import {Actions} from "@ngneat/effects-ng";
        | ^
      3 | import {loadApp} from "./app.effects";
      4 |
      5 | @Component({

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1495:14)
      at Object.<anonymous> (src/app/app.component.ts:2:1)
      at Object.<anonymous> (src/app/app.component.spec.ts:2:1)
```

### Please provide the environment you discovered this bug in

```true
"@ngneat/effects": "2.1.1",
    "jest": "29.x",

also on 

    "jest": "28.x",
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
@EricPoul

**Comment by NetanelBasal** [comment]
https://github.com/thymikee/jest-preset-angular/issues/1149

**Comment by guysenpai** [comment]
> [thymikee/jest-preset-angular#1149](https://github.com/thymikee/jest-preset-angular/issues/1149)

I have the same issue and nothing in the link above works. I'm working on a Nx 15.9 monorepo with angular 15.2 and jest-preset-angular 13
