### ISSUE TITLE
effects-ng installation problems

### ISSUE THREAD

**Issue by ericwfisher** [ngneat/effects#51]
There seems to be dependency discrepancies between the different Elf packages. Elf and other packages depend on an exact version of 15.2.4 for angular packages but Effects depends on exact versions of 15.1.4 for angular packages. Since updating Elf packages to the latest I cannot install without `--force`. Is it possible to either fix the differing exact version dependencies or use more flexible semver?

### Discussed in https://github.com/ngneat/effects/discussions/50

<div type='discussions-op-text'>

<sup>Originally posted by **ericwfisher** March 28, 2023</sup>
Anyone else here having issues installing `@ngneat/effects-ng@3.1.0` due to a reported dependency on `@angular/router@15.1.4`? 
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myapp@0.0.0
npm ERR! Found: @angular/router@15.2.4
npm ERR! node_modules/@angular/router
npm ERR!   @angular/router@"^15.2.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/router@"15.1.4" from @ngneat/effects-ng@3.1.0
npm ERR! node_modules/@ngneat/effects-ng
npm ERR!   @ngneat/effects-ng@"^3.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See ~/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!    ~/.npm/_logs/2023-03-28T17_54_27_983Z-debug-0.log
```

**Comment by NetanelBasal** [comment]
Done
