### ISSUE TITLE
Multiple effects with same class and function names

### ISSUE THREAD

**Issue by nickathone** [ngneat/effects#60]
### Which @ngneat/effects-* package(s) are the source of the bug?

effects, effects-ng

### Is this a regression?

Yes

### Description

Previously using v2 of `effects-ng` I could register multiple effects classes with the same name, as well as properties with the same name. 

However, having recently updated to v3, and changed to using `provideEffectsManager` and `provideEffects` it seems only the first effect class is registered and all others are ignored.

Hopefully, this illustrates the issue:

```
// Module 1
export class DataEffects {
    readonly fetch$ = createEffect((actions) =>
        actions.pipe(
            ofType(dataActions.fetch),
            switchMap(<call to API 1>),
       ),
    );
}

// Module 2
export class DataEffects {
    readonly fetch$ = createEffect((actions) =>
        actions.pipe(
            ofType(dataActions.fetch),
            switchMap(<call to API 2>),
       ),
    );
}

//----- THIS WORKED [v2]

// Module 1
EffectsNgModule.forFeature([DataEffects])

// Module 2
EffectsNgModule.forFeature([DataEffects])

//----- THIS DOES NOT WORK [v3] (only provideEffects to be registered first works)

// Module 1
provideEffects(DataEffects)

// Module 2
provideEffects(DataEffects)
```

### Please provide the environment you discovered this bug in

```true
@angular/*: 16.0.4
@ngneat/effects-ng: 3.1.2
```

### Do you want to create a pull request?

No

**Comment by nickathone** [comment]
I created a StackBlitz replicating the issue:
https://stackblitz.com/edit/stackblitz-starters-wg1fa5?file=src%2Fmodule.ts

**Comment by NetanelBasal** [comment]
@EricPoul

**Comment by EricPoul** [comment]
@nickathone please update the latest version to check if it works

**Comment by nickathone** [comment]
@EricPoul I have tested your change via a local build of the master branch. Seems to be working as expected now. 

When will this be pushed to npm?

Thanks 👍

**Comment by EricPoul** [comment]
@NetanelBasal

**Comment by NetanelBasal** [comment]
Done
